replicaCount: 1

image:
  repository: louislam/uptime-kuma
  pullPolicy: IfNotPresent
  tag: "2.0.2"

service:
  name: uptime-kuma
  type: NodePort
  port: 3001
  nodePort: 32222

persistence:
  enabled: true
  claimName: uptime-kuma-data
  mountPath: /app/data
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  size: 1Gi

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
