{{- $app := index .Values.applications "uptime-kuma" -}}
{{- if and $app $app.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: uptime-kuma
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $app.project }}
  source:
    repoURL: {{ .Values.global.repoURL }}
    path: charts/uptime-kuma
    targetRevision: {{ .Values.global.targetRevision }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $app.namespace }}
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}
