# Global settings for all ArgoCD Applications
global:
  repoURL: https://github.com/fwafa-devops/cni-example
  targetRevision: HEAD

# Application configurations
applications:
  webapp-color:
    enabled: true
    project: default
    namespace: webapp-color
  jenkins-test:
    enabled: true
    project: default
    namespace: jenkins
  uptime-kuma:
    enabled: true
    project: default
    namespace: uptime-kuma